x-veld:
  code:
    about:
      description: "Downloads a txt file given the url, and prepares it for word2vec training"
      topics: 
        - "ETL"
        - "NLP"

    outputs:
      volume: /veld/output/
      file_formats: "txt"
      contents: 
        - "NLP training data"
        - "NLP data"
        - "word2vec training data"

    environment:
      in_url:
        description: "url of a txt file"
        type: url
      out_file:
        description: "name of training data file"
        type: file
        volume: /veld/output/

services:
  veld:
    build: .
    command: python /veld/code/preprocess.py
    volumes:
      - ./src/:/veld/code/
      - ./data/:/veld/output/
    environment:
      in_url: null
      out_file: null

