x-veld:
  code:
    # TODO

services:
  veld:
    build: .
    command: python /veld/code/preprocess.py
    volumes:
      - ./src/:/veld/code/
      - ./data/:/veld/output/
    environment:
      out_file: "bible.txt"

